# Generated by Django 3.1.4 on 2020-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectdescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='projectlink',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='projectsummary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='projecttitle',
            field=models.TextField(default=''),
        ),
    ]
