# Generated by Django 3.1.4 on 2020-12-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20201213_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectdescription',
            new_name='FullDescription',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectlink',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectsummary',
            new_name='Summary',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projecttitle',
            new_name='Title',
        ),
    ]
