# Generated by Django 3.1.4 on 2020-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20201213_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='Title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
